title: Worcester Source
url: "https://worcestersoure.club"
baseurl:
google_analytics_key: UA-118295633-3
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Worcester Source is a monthly meetup group hosted on the fourth Wednesday of each month in the back-room of the Paul Pry pub in central Worcester.

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Worcester Source
  links:
    - https://github.com/worcester-space/worcestersource.club

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

plugins_dir: ./_plugins

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# Jekyll Get
jekyll_get:
  - data: upcoming_events
    json: 'https://api.meetup.com/Worcester-Source-Meetup/events?&sign=true&photo-host=secure&fields=featured_photo'
  - data: past_events
    json: 'https://api.meetup.com/Worcester-Source-Meetup/events?&sign=true&photo-host=secure&fields=featured_photo&desc=true&status=past'
